server: 1ca71cd6-08c4-4855-9381-2f41aeffe59c
environment: development
private_key_file: spec/private_key.pem
loglevel: debug
berksfile: spec/test_berksfile
json_file: spec/test_json_file
cached: false
api_url: https://www.riyic.com/api/v1
download_tarball: https://www.riyic.com/cookbooks.tar.gz
